import * as ec2 from "aws-cdk-lib/aws-ec2";
import * as iam from 'aws-cdk-lib/aws-iam';
import * as ecr from 'aws-cdk-lib/aws-ecr';
import * as r53 from "aws-cdk-lib/aws-route53";
import { RemovalPolicy, Stack, StackProps } from 'aws-cdk-lib';
import { Construct } from 'constructs';

export class RuntimeStack extends Stack {
    private readonly httpPort = 80;
    private readonly httpsPort = 443;
    private readonly inboundTrafficPorts = [this.httpPort, this.httpsPort];
    public readonly HOST_INSTANCE_TAG_NAME = 'calebpirkle-host';
    public readonly ECR_REPOSITORY: ecr.Repository;
    public readonly INSTANCE_ROLE: iam.Role;

    constructor(scope: Construct, id: string, props?: StackProps) {
        super(scope, id, props);

        const vpc = new ec2.Vpc(this, 'Vpc', {
            vpcName: 'calebpirkle-vpc',
            createInternetGateway: true,
            ipAddresses: ec2.IpAddresses.cidr('10.0.0.0/24'),
            ipProtocol: ec2.IpProtocol.IPV4_ONLY,
            maxAzs: 1,
            natGateways: 0,
            enableDnsHostnames: true,
            enableDnsSupport: true,
            vpnGateway: false,
            restrictDefaultSecurityGroup: true,
            subnetConfiguration: [
                {
                    cidrMask: 24,
                    name: 'ingress',
                    subnetType: ec2.SubnetType.PUBLIC,
                },
            ]
        });

        const instanceSecurityGroup = new ec2.SecurityGroup(this, 'InstanceSecurityGroup', {
            vpc,
            securityGroupName: 'calebpirkle-instance-sg',
            description: 'ec2 security group for calebpirkle.com',
            allowAllIpv6Outbound: false,
            allowAllOutbound: true,
            disableInlineRules: false,
            // no inbound rules by default
        });

        const instanceRole = new iam.Role(this, 'InstanceRole', {
            roleName: 'calebpirkle-instance-role',
            assumedBy: new iam.ServicePrincipal('ec2.amazonaws.com'),
            managedPolicies: [
                iam.ManagedPolicy.fromAwsManagedPolicyName('AmazonSSMManagedInstanceCore'),
                iam.ManagedPolicy.fromAwsManagedPolicyName('AmazonEC2ContainerRegistryReadOnly')
            ],
        });

        const userData = ec2.UserData.forLinux();
        userData.addCommands(
            'dnf update -y',
            'dnf install -y docker',
            'systemctl enable docker',
            'systemctl start docker',
            'usermod -a -G docker ec2-user',
        );

        const hostInstance = new ec2.Instance(this, 'HostInstance', {
            vpc,
            instanceName: this.HOST_INSTANCE_TAG_NAME,
            instanceType: ec2.InstanceType.of(ec2.InstanceClass.T4G, ec2.InstanceSize.NANO),
            machineImage: ec2.MachineImage.latestAmazonLinux2023({
                cpuType: ec2.AmazonLinuxCpuType.ARM_64
            }),
            vpcSubnets: { subnetType: ec2.SubnetType.PUBLIC },
            securityGroup: instanceSecurityGroup,
            role: instanceRole,
            userData,
        });

        // restrict traffic to 80 and 443 on instance, this updates the security group
        this.inboundTrafficPorts.forEach(
            port => hostInstance.connections.allowFrom(
                ec2.Peer.anyIpv4(), ec2.Port.tcp(port),
                'Allow incoming www http/s traffic to calebpirkle.com instance'
            )
        );

        const eip = new ec2.CfnEIP(this, 'ElasticIp', {
            domain: 'vpc'
        });

        // associate eip with ec2 instance
        new ec2.CfnEIPAssociation(this, 'EipAssociation', {
            instanceId: hostInstance.instanceId,
            allocationId: eip.attrAllocationId
        });

        const hostedZone = new r53.HostedZone(this, 'HostedZone', {
            zoneName: "calebpirkle.com"
        });
        new r53.ARecord(this, 'NonWWWARecord', {
            zone: hostedZone,
            target: r53.RecordTarget.fromIpAddresses(eip.ref),
        });
        new r53.ARecord(this, 'WwwARecord', {
            zone: hostedZone,
            target: r53.RecordTarget.fromIpAddresses(eip.ref),
            recordName: "www"
        });
        // NS and SOA records are generated by CDK

        const ecrRepository = new ecr.Repository(this, 'EcrRepository', {
            repositoryName: 'calebpirkle/site',
            emptyOnDelete: true,
            removalPolicy: RemovalPolicy.DESTROY,
            imageTagMutability: ecr.TagMutability.MUTABLE,
            lifecycleRules: [
                {
                    description: 'Keep only the latest two images',
                    maxImageCount: 2
                }
            ]
        });

        this.ECR_REPOSITORY = ecrRepository;
        this.INSTANCE_ROLE = instanceRole;
    }
}